version: "3.9"
services:
  app-blue:
    image: your-spring-boot-image:latest
    ports:
      - "8081:8081"
    environment:
      - SPRING_PROFILES_ACTIVE=blue
    depends_on:
      mysql-blue:
        condition: service_healthy
  mysql-blue:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: your_root_password
      MYSQL_DATABASE: your_database
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  mysql_data_blue:
