services:
  app-green:
    container_name: app-green
    image: your-spring-boot-image:latest
    ports:
      - "8082:8081"
    environment:
      - SPRING_PROFILES_ACTIVE=green
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql-green:3306/project
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=rootpassword123
    depends_on:
      mysql-green:
        condition: service_healthy

  mysql-green:
    container_name: mysql-green
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=rootpassword123
      - MYSQL_DATABASE=project
      - MYSQL_USER=springuser
      - MYSQL_PASSWORD=springpassword
      - MYSQL_ROOT_HOST=%
    ports:
      - "3308:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  mysql_data_green:
