version: "3.9"
services:
  app-green:
    image: your-spring-boot-image:latest
    ports:
      - "8082:8081" # Expose on port 8081 for green
    environment:
      - SPRING_PROFILES_ACTIVE=green # Optional: Spring profiles
    depends_on:
      - mysql-green
  mysql-green:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: your_root_password
      MYSQL_DATABASE: your_database
    ports:
      - "3307:3306"
    volumes:
      - mysql_data_green:/var/lib/mysql
volumes:
  mysql_data_green: