---
- name: Deploy NGINX Blue-Green Configuration
  hosts: localhost
  become: yes
  vars:
    current_color: "{{ TARGET_ENVIRONMENT | default('blue') }}"  # Defaults to blue if not specified

  tasks:
    - name: Ensure NGINX is installed
      apt:
        name: nginx
        state: present
        update_cache: yes

    - name: Set NGINX configuration for blue-green deployment
      template:
        src: templates/nginx.conf.j2
        dest: /etc/nginx/sites-available/default
        owner: root
        group: root
        mode: '0644'
        validate: 'nginx -t -c %s'
      notify:
        - restart nginx

    - name: Create symlink for NGINX configuration
      file:
        src: /etc/nginx/sites-available/default
        dest: /etc/nginx/sites-enabled/default
        state: link
        force: yes
      notify:
        - restart nginx

    - name: Remove default NGINX configuration if exists
      file:
        path: /etc/nginx/sites-enabled/default.conf
        state: absent
      notify:
        - restart nginx

    - name: Test NGINX configuration
      command: nginx -t
      register: nginx_test
      failed_when: nginx_test.rc != 0
      changed_when: false

    - name: Ensure NGINX is started and enabled
      service:
        name: nginx
        state: started
        enabled: yes

  handlers:
    - name: restart nginx
      service:
        name: nginx
        state: restarted

